In [1]:
import bioframe as bf
import pandas as pd

In [12]:
#dataset = "mendelian_traits_matched_9"
dataset = "complex_traits_matched_9"
V = pd.read_parquet(f"../../results/dataset/{dataset}/test.parquet")
V

,chrom,pos,ref,alt,pip,trait,label,maf,ld_score,consequence,tss_dist,match_group
0,1,867476,C,T,0.001560,,False,0.079465,44.053,non_coding_transcript_exon_variant,56446,non_coding_transcript_exon_variant_0
1,1,868052,T,C,0.001791,,False,0.077747,44.057,non_coding_transcript_exon_variant,55870,non_coding_transcript_exon_variant_0
2,1,868635,A,G,0.004349,,False,0.075255,43.639,non_coding_transcript_exon_variant,55287,non_coding_transcript_exon_variant_0
3,1,870176,T,A,0.000000,,False,0.084371,37.271,non_coding_transcript_exon_variant,53746,non_coding_transcript_exon_variant_0
4,1,1052930,A,G,0.001467,,False,0.058385,46.907,non_coding_transcript_exon_variant,18823,non_coding_transcript_exon_variant_1
...,...,...,...,...,...,...,...,...,...,...,...,...
11395,22,50368376,T,C,0.000000,,False,0.191810,86.507,dELS,3695,dELS_204
11396,22,50571623,C,T,0.000000,,False,0.061159,23.900,dELS,6291,dELS_202
11397,22,50671289,G,A,0.000000,,False,0.036223,12.733,pELS_flank,3125,pELS_flank_26
11398,22,50713837,C,G,0.000000,,False,0.060562,20.896,dELS,8340,dELS_202
11399,22,50783672,G,T,0.000000,,False,0.054650,43.615,PLS,4,PLS_21

In [3]:
tss = pd.read_parquet("../../results/tss.parquet")
tss

      chrom    start      end          gene_id
0         1  1471764  1471765  ENSG00000160072
1         1  1471783  1471784  ENSG00000160072
2         1  3069167  3069168  ENSG00000142611
3         1  3069196  3069197  ENSG00000142611
4         1  3069210  3069211  ENSG00000142611
...     ...      ...      ...              ...
88709    MT    10469    10470  ENSG00000212907
88710    MT    10759    10760  ENSG00000198886
88711    MT    12336    12337  ENSG00000198786
88712    MT    14672    14673  ENSG00000198695
88713    MT    14746    14747  ENSG00000198727

[88714 rows x 4 columns]

In [13]:
V["start"] = V.pos - 1
V["end"] = V.pos
V = bf.closest(V, tss).rename(columns={
    "gene_id_": "gene",
}).drop(columns=["start", "end", "chrom_", "start_", "end_", "distance"])
V

/scratch/users/gbenegas/software/mambaforge/envs/gpn/lib/python3.11/site-packages/bioframe/core/specs.py:150: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  pd.api.types.is_categorical_dtype(chrom_dtype),
/scratch/users/gbenegas/software/mambaforge/envs/gpn/lib/python3.11/site-packages/bioframe/core/specs.py:150: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  pd.api.types.is_categorical_dtype(chrom_dtype),

,chrom,pos,ref,alt,pip,trait,label,maf,ld_score,consequence,tss_dist,match_group,gene
0,1,867476,C,T,0.001560,,False,0.079465,44.053,non_coding_transcript_exon_variant,56446,non_coding_transcript_exon_variant_0,ENSG00000187634
1,1,868052,T,C,0.001791,,False,0.077747,44.057,non_coding_transcript_exon_variant,55870,non_coding_transcript_exon_variant_0,ENSG00000187634
2,1,868635,A,G,0.004349,,False,0.075255,43.639,non_coding_transcript_exon_variant,55287,non_coding_transcript_exon_variant_0,ENSG00000187634
3,1,870176,T,A,0.000000,,False,0.084371,37.271,non_coding_transcript_exon_variant,53746,non_coding_transcript_exon_variant_0,ENSG00000187634
4,1,1052930,A,G,0.001467,,False,0.058385,46.907,non_coding_transcript_exon_variant,18823,non_coding_transcript_exon_variant_1,ENSG00000188157
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11395,9,137295393,T,G,0.000000,,False,0.069513,28.104,non_coding_transcript_exon_variant,6877,non_coding_transcript_exon_variant_66,ENSG00000198435
11396,9,137464104,C,T,0.991337,eGFR,True,0.079915,19.442,dELS_flank,4769,dELS_flank_166,ENSG00000165802
11397,9,137467007,A,G,0.000000,,False,0.100090,27.121,dELS,7672,dELS_306,ENSG00000165802
11398,9,137880269,T,C,0.000000,,False,0.488870,44.687,dELS_flank,2334,dELS_flank_160,ENSG00000148408
11399,9,138123517,C,T,0.002499,,False,0.375020,94.959,3_prime_UTR_variant,47647,3_prime_UTR_variant_50,ENSG00000148408

In [14]:
#V.to_csv("mendelian_traits.csv.gz", index=False)
V.to_csv("complex_traits.csv.gz", index=False)

In [15]:
#pd.read_csv("mendelian_traits.csv.gz")
pd.read_csv("complex_traits.csv.gz")

,chrom,pos,ref,alt,pip,trait,label,maf,ld_score,consequence,tss_dist,match_group,gene
0,1,867476,C,T,0.001560,NaN,False,0.079465,44.053,non_coding_transcript_exon_variant,56446,non_coding_transcript_exon_variant_0,ENSG00000187634
1,1,868052,T,C,0.001791,NaN,False,0.077747,44.057,non_coding_transcript_exon_variant,55870,non_coding_transcript_exon_variant_0,ENSG00000187634
2,1,868635,A,G,0.004349,NaN,False,0.075255,43.639,non_coding_transcript_exon_variant,55287,non_coding_transcript_exon_variant_0,ENSG00000187634
3,1,870176,T,A,0.000000,NaN,False,0.084371,37.271,non_coding_transcript_exon_variant,53746,non_coding_transcript_exon_variant_0,ENSG00000187634
4,1,1052930,A,G,0.001467,NaN,False,0.058385,46.907,non_coding_transcript_exon_variant,18823,non_coding_transcript_exon_variant_1,ENSG00000188157
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11395,9,137295393,T,G,0.000000,NaN,False,0.069513,28.104,non_coding_transcript_exon_variant,6877,non_coding_transcript_exon_variant_66,ENSG00000198435
11396,9,137464104,C,T,0.991337,eGFR,True,0.079915,19.442,dELS_flank,4769,dELS_flank_166,ENSG00000165802
11397,9,137467007,A,G,0.000000,NaN,False,0.100090,27.121,dELS,7672,dELS_306,ENSG00000165802
11398,9,137880269,T,C,0.000000,NaN,False,0.488870,44.687,dELS_flank,2334,dELS_flank_160,ENSG00000148408
11399,9,138123517,C,T,0.002499,NaN,False,0.375020,94.959,3_prime_UTR_variant,47647,3_prime_UTR_variant_50,ENSG00000148408

In [17]:
df = pd.read_parquet("../../results/dataset/complex_traits_v2_nonexonic_matched_1/test.parquet")

,chrom,pos,ref,alt,pip,trait,label,maf,ld_score,consequence,gene,tss_dist,match_group
0,1,2293397,G,A,0.999932,Height,True,0.370570,32.302,dELS,ENSG00000157933,65077,dELS_0
1,1,2299360,T,C,0.002934,,False,0.370500,36.621,dELS,ENSG00000157933,71040,dELS_0
2,1,3080038,T,C,0.999895,"MCH,MCV,Plt,RBC",True,0.232720,31.606,dELS,ENSG00000142611,10826,dELS_1
3,1,3409530,C,G,0.000537,,False,0.234330,33.908,dELS,ENSG00000142611,13038,dELS_1
4,1,3774964,A,G,0.999973,"Hb,HbA1c,MCHC,RBC",True,0.230570,95.317,dELS,ENSG00000235169,2138,dELS_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1925,22,46223973,T,G,0.002961,,False,0.218360,167.290,dELS_flank,ENSG00000205643,24311,dELS_flank_108
1926,22,47990921,C,T,0.997536,BMI,True,0.437610,53.514,intron_variant,ENSG00000219438,498631,intron_variant_124
1927,22,49172564,A,G,0.000000,,False,0.429700,52.727,intron_variant,ENSG00000219438,479316,intron_variant_124
1928,22,50190508,G,A,1.000000,Plt,True,0.072852,57.970,PLS,ENSG00000170638,89,PLS_17
1929,22,50190675,G,A,0.000000,,False,0.017765,35.685,PLS,ENSG00000170638,76,PLS_17