In [3]:
import pandas as pd

In [4]:
V = pd.read_parquet("../../results/clinvar/all.annot.parquet")
V

     chrom        pos ref alt       consequence
0        1   11114338   A   G  missense_variant
1        1   11124516   G   A  missense_variant
2        1   11124516   G   T  missense_variant
3        1   11128107   G   C  missense_variant
4        1   11128107   G   T  missense_variant
...    ...        ...  ..  ..               ...
3131     X  154966634   G   A       stop_gained
3132     X  154969361   G   C  missense_variant
3133     X  154969417   G   A  missense_variant
3134     X  154984788   G   T       stop_gained
3135     X  154992938   T   C  missense_variant

[3136 rows x 5 columns]

In [6]:
df = V.consequence.value_counts().to_frame().reset_index()
df

                            consequence  count
0                           stop_gained   1687
1                      missense_variant    988
2                  splice_donor_variant    177
3               splice_acceptor_variant    157
4                            start_lost     33
5                 splice_region_variant     23
6         splice_donor_5th_base_variant     22
7   splice_polypyrimidine_tract_variant     20
8           splice_donor_region_variant     13
9                        intron_variant      6
10                   synonymous_variant      5
11                            stop_lost      3
12                  3_prime_UTR_variant      1
13                upstream_gene_variant      1

In [7]:
df.consequence = r"\verb|" + df.consequence + r"|"
df

                                   consequence  count
0                           \verb|stop_gained|   1687
1                      \verb|missense_variant|    988
2                  \verb|splice_donor_variant|    177
3               \verb|splice_acceptor_variant|    157
4                            \verb|start_lost|     33
5                 \verb|splice_region_variant|     23
6         \verb|splice_donor_5th_base_variant|     22
7   \verb|splice_polypyrimidine_tract_variant|     20
8           \verb|splice_donor_region_variant|     13
9                        \verb|intron_variant|      6
10                   \verb|synonymous_variant|      5
11                            \verb|stop_lost|      3
12                  \verb|3_prime_UTR_variant|      1
13                \verb|upstream_gene_variant|      1

In [8]:
print(df.to_latex(index=False))

\begin{tabular}{lr}
\toprule
consequence & count \\
\midrule
\verb|stop_gained| & 1687 \\
\verb|missense_variant| & 988 \\
\verb|splice_donor_variant| & 177 \\
\verb|splice_acceptor_variant| & 157 \\
\verb|start_lost| & 33 \\
\verb|splice_region_variant| & 23 \\
\verb|splice_donor_5th_base_variant| & 22 \\
\verb|splice_polypyrimidine_tract_variant| & 20 \\
\verb|splice_donor_region_variant| & 13 \\
\verb|intron_variant| & 6 \\
\verb|synonymous_variant| & 5 \\
\verb|stop_lost| & 3 \\
\verb|3_prime_UTR_variant| & 1 \\
\verb|upstream_gene_variant| & 1 \\
\bottomrule
\end{tabular}