In [1]:
import pandas as pd

In [24]:
dataset = "mendelian_traits_matched_9"
base_dir = f"../../results/dataset/{dataset}"
V = pd.read_parquet(f"{base_dir}/test.parquet")
V

,chrom,pos,ref,alt,OMIM,consequence,label,tss_dist,match_group
0,1,1425822,C,G,None,PLS,False,48,PLS_4
1,1,1615869,C,T,None,PLS,False,35,PLS_0
2,1,1659060,G,A,None,PLS,False,47,PLS_4
3,1,1659114,A,G,None,PLS,False,101,PLS_5
4,1,2050958,T,C,None,5_prime_UTR_variant,False,149,5_prime_UTR_variant_7
...,...,...,...,...,...,...,...,...,...
3375,X,155613005,C,T,None,PLS,False,52,PLS_52
3376,X,155719093,C,A,None,5_prime_UTR_variant,False,4,5_prime_UTR_variant_101
3377,X,155881342,A,C,None,PLS,False,2,PLS_57
3378,X,155881414,C,T,None,5_prime_UTR_variant,False,35,5_prime_UTR_variant_110
3379,X,156020793,A,G,None,upstream_gene_variant,False,167,upstream_gene_variant_9

In [25]:
models = [
    "GPN-MSA_LLR.minus.score",
    "Enformer_L2_L2.plus.all",
    "Borzoi_L2_L2.plus.all",
    "CADD.plus.RawScore",

    "GPN_LLR.minus.score",
    "NucleotideTransformer_LLR.minus.score",
]

for model in models:
    df = (
        pd.read_parquet(f"{base_dir}/preds/all/{model}.parquet")
        .rename(columns={"score": model})
    )
    V = pd.concat([V, df], axis=1)
V

,chrom,pos,ref,alt,OMIM,consequence,label,tss_dist,match_group,GPN-MSA_LLR.minus.score,Enformer_L2_L2.plus.all,Borzoi_L2_L2.plus.all,CADD.plus.RawScore,GPN_LLR.minus.score,NucleotideTransformer_LLR.minus.score
0,1,1425822,C,G,None,PLS,False,48,PLS_4,-3.439453,4.809692,17.851372,0.641057,0.282471,-0.332962
1,1,1615869,C,T,None,PLS,False,35,PLS_0,-0.529785,16.235533,42.570778,0.168522,2.089844,1.943222
2,1,1659060,G,A,None,PLS,False,47,PLS_4,0.802246,11.277819,20.612617,0.040859,0.127075,0.023132
3,1,1659114,A,G,None,PLS,False,101,PLS_5,-4.070312,70.224617,182.252731,0.962354,-4.367188,-3.802872
4,1,2050958,T,C,None,5_prime_UTR_variant,False,149,5_prime_UTR_variant_7,-1.386719,6.366479,20.020468,0.382432,0.021240,-1.201019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3375,X,155613005,C,T,None,PLS,False,52,PLS_52,-1.066406,12.772987,23.422033,-0.046796,-0.186157,-0.208862
3376,X,155719093,C,A,None,5_prime_UTR_variant,False,4,5_prime_UTR_variant_101,-0.505859,19.870684,50.873600,0.301978,-0.408691,2.122528
3377,X,155881342,A,C,None,PLS,False,2,PLS_57,3.859375,10.854235,40.226589,0.325166,-0.103699,-0.230331
3378,X,155881414,C,T,None,5_prime_UTR_variant,False,35,5_prime_UTR_variant_110,1.322266,12.183937,27.444807,0.412759,1.541016,1.868652
3379,X,156020793,A,G,None,upstream_gene_variant,False,167,upstream_gene_variant_9,2.289062,14.320102,56.000462,-0.390194,0.817383,-1.790924

In [26]:
variant_pos = 113105781
match_group = V[V.pos==variant_pos].match_group.iloc[0]
V = V[V.match_group==match_group]
V

,chrom,pos,ref,alt,OMIM,consequence,label,tss_dist,match_group,GPN-MSA_LLR.minus.score,Enformer_L2_L2.plus.all,Borzoi_L2_L2.plus.all,CADD.plus.RawScore,GPN_LLR.minus.score,NucleotideTransformer_LLR.minus.score
2024,13,19783080,C,T,None,PLS,False,60,PLS_17,-1.063477,6.382195,12.287943,-0.541764,0.729492,1.113190
2078,13,38687014,T,G,None,PLS,False,62,PLS_17,2.125000,12.220740,25.388615,0.519610,0.103027,-0.323212
2086,13,43879803,C,T,None,PLS,False,62,PLS_17,-0.985840,15.553901,70.023598,0.015686,0.297607,1.465607
2093,13,44474362,C,G,None,PLS,False,60,PLS_17,1.953125,18.147209,30.625559,0.831735,-0.006409,0.227692
2097,13,46142912,T,C,None,PLS,False,72,PLS_17,4.015625,20.243399,41.274086,0.805389,1.883789,3.634064
2136,13,60396407,T,C,None,PLS,False,49,PLS_17,-0.192871,9.533968,23.988342,0.443120,-2.230469,-3.243607
2150,13,78603624,C,A,None,PLS,False,71,PLS_17,7.890625,21.970518,68.232132,2.715072,2.505859,3.120804
2180,13,103066474,G,A,None,PLS,False,56,PLS_17,-2.691406,7.186910,29.977983,0.295569,-0.072266,0.023895
2207,13,113105720,T,C,None,PLS,False,67,PLS_17,0.568848,9.405406,16.074432,0.293926,-0.707520,-1.606476
2209,13,113105781,T,G,MIM 227500,PLS,True,6,PLS_17,8.890625,123.875313,207.104034,2.142261,3.224609,1.339050

In [27]:
for model in models:
    V[f"rank_{model}"] = V[model].rank(ascending=False)
V.loc[V.label, [f"rank_{model}" for model in models]]

/tmp/ipykernel_3275842/2749493244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  V[f"rank_{model}"] = V[model].rank(ascending=False)
/tmp/ipykernel_3275842/2749493244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  V[f"rank_{model}"] = V[model].rank(ascending=False)
/tmp/ipykernel_3275842/2749493244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  V[f"rank_{model}"] = V[model].rank(ascending=False)
/tmp/ipykernel_3275842/2749493244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  V[f"rank_{model}"] = V[model].rank(ascending=False)
/tmp/ipykernel_3275842/2749493244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  V[f"rank_{model}"] = V[model].rank(ascending=False)
/tmp/ipykernel_3275842/2749493244.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  V[f"rank_{model}"] = V[model].rank(ascending=False)

,rank_GPN-MSA_LLR.minus.score,rank_Enformer_L2_L2.plus.all,rank_Borzoi_L2_L2.plus.all,rank_CADD.plus.RawScore,rank_GPN_LLR.minus.score,rank_NucleotideTransformer_LLR.minus.score
2209,1.0,1.0,1.0,2.0,1.0,4.0

In [29]:
# TODO: could get the pairwise dependency of the variant according to 
# both GPN and GPN-MSA! maybe GPN better for this
# (also get the latest version of gLM-Promoter)
# (should also plot the marginal reconstruction logo plot according to the two models)
# I wonder if should just run this in the CPU even?
# at least for now, can just run it in a notebook